server:
  port: 9000
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/demo
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

 
